# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainView.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(651, 510)
        self.tabs = QtWidgets.QTabWidget(Form)
        self.tabs.setGeometry(QtCore.QRect(0, 10, 651, 501))
        self.tabs.setObjectName("tabs")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.makeCalculationButton = QtWidgets.QPushButton(self.tab_6)
        self.makeCalculationButton.setGeometry(QtCore.QRect(320, 430, 89, 25))
        self.makeCalculationButton.setObjectName("makeCalculationButton")
        self.addItemButton = QtWidgets.QPushButton(self.tab_6)
        self.addItemButton.setGeometry(QtCore.QRect(185, 430, 131, 25))
        self.addItemButton.setObjectName("addItemButton")
        self.label_12 = QtWidgets.QLabel(self.tab_6)
        self.label_12.setGeometry(QtCore.QRect(10, 10, 171, 17))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.tab_6)
        self.label_13.setGeometry(QtCore.QRect(430, 10, 161, 17))
        self.label_13.setObjectName("label_13")
        self.producedItemsTable = QtWidgets.QTableView(self.tab_6)
        self.producedItemsTable.setGeometry(QtCore.QRect(10, 30, 401, 391))
        self.producedItemsTable.setObjectName("producedItemsTable")
        self.producedItemsRestrictionsTable = QtWidgets.QTableView(self.tab_6)
        self.producedItemsRestrictionsTable.setGeometry(QtCore.QRect(420, 30, 221, 261))
        self.producedItemsRestrictionsTable.setObjectName("producedItemsRestrictionsTable")
        self.groupBox = QtWidgets.QGroupBox(self.tab_6)
        self.groupBox.setGeometry(QtCore.QRect(420, 290, 221, 131))
        self.groupBox.setObjectName("groupBox")
        self.formLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.formLayoutWidget.setGeometry(QtCore.QRect(9, 29, 202, 89))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_14 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_14.setObjectName("label_14")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.maxProdCriteria = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.maxProdCriteria.setObjectName("maxProdCriteria")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.maxProdCriteria)
        self.label_15 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_15.setObjectName("label_15")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.minCostCriteria = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.minCostCriteria.setObjectName("minCostCriteria")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.minCostCriteria)
        self.label_16 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_16.setObjectName("label_16")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.maxProfitCriteria = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.maxProfitCriteria.setObjectName("maxProfitCriteria")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.maxProfitCriteria)
        self.loadButton = QtWidgets.QPushButton(self.tab_6)
        self.loadButton.setGeometry(QtCore.QRect(455, 430, 89, 25))
        self.loadButton.setObjectName("loadButton")
        self.saveButton = QtWidgets.QPushButton(self.tab_6)
        self.saveButton.setGeometry(QtCore.QRect(550, 430, 89, 25))
        self.saveButton.setObjectName("saveButton")
        self.tabs.addTab(self.tab_6, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.label_10 = QtWidgets.QLabel(self.tab_5)
        self.label_10.setGeometry(QtCore.QRect(10, 10, 111, 17))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.tab_5)
        self.label_11.setGeometry(QtCore.QRect(330, 10, 111, 17))
        self.label_11.setObjectName("label_11")
        self.wholesalePricesTable = QtWidgets.QTableView(self.tab_5)
        self.wholesalePricesTable.setGeometry(QtCore.QRect(10, 30, 311, 421))
        self.wholesalePricesTable.setObjectName("wholesalePricesTable")
        self.costPriceTable = QtWidgets.QTableView(self.tab_5)
        self.costPriceTable.setGeometry(QtCore.QRect(330, 30, 311, 421))
        self.costPriceTable.setObjectName("costPriceTable")
        self.tabs.addTab(self.tab_5, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(10, 10, 191, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(430, 10, 141, 17))
        self.label_2.setObjectName("label_2")
        self.addEmployeeButton = QtWidgets.QPushButton(self.tab)
        self.addEmployeeButton.setGeometry(QtCore.QRect(10, 430, 161, 25))
        self.addEmployeeButton.setObjectName("addEmployeeButton")
        self.salaryTotalBudget = QtWidgets.QLineEdit(self.tab)
        self.salaryTotalBudget.setGeometry(QtCore.QRect(390, 430, 251, 25))
        self.salaryTotalBudget.setObjectName("salaryTotalBudget")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(250, 430, 141, 20))
        self.label_3.setObjectName("label_3")
        self.laborCostsTable = QtWidgets.QTableView(self.tab)
        self.laborCostsTable.setGeometry(QtCore.QRect(10, 30, 411, 391))
        self.laborCostsTable.setObjectName("laborCostsTable")
        self.salaryTable = QtWidgets.QTableView(self.tab)
        self.salaryTable.setGeometry(QtCore.QRect(430, 30, 211, 391))
        self.salaryTable.setObjectName("salaryTable")
        self.tabs.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 111, 17))
        self.label_6.setObjectName("label_6")
        self.addRawMaterialKindButton = QtWidgets.QPushButton(self.tab_2)
        self.addRawMaterialKindButton.setGeometry(QtCore.QRect(10, 430, 151, 25))
        self.addRawMaterialKindButton.setObjectName("addRawMaterialKindButton")
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(430, 10, 111, 17))
        self.label_7.setObjectName("label_7")
        self.rawMaterialConsumptionTable = QtWidgets.QTableView(self.tab_2)
        self.rawMaterialConsumptionTable.setGeometry(QtCore.QRect(10, 30, 411, 391))
        self.rawMaterialConsumptionTable.setObjectName("rawMaterialConsumptionTable")
        self.rawMaterialResourcesTable = QtWidgets.QTableView(self.tab_2)
        self.rawMaterialResourcesTable.setGeometry(QtCore.QRect(430, 30, 211, 391))
        self.rawMaterialResourcesTable.setObjectName("rawMaterialResourcesTable")
        self.tabs.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_8 = QtWidgets.QLabel(self.tab_3)
        self.label_8.setGeometry(QtCore.QRect(20, 10, 131, 17))
        self.label_8.setObjectName("label_8")
        self.addRangeGroupButton = QtWidgets.QPushButton(self.tab_3)
        self.addRangeGroupButton.setGeometry(QtCore.QRect(10, 430, 181, 25))
        self.addRangeGroupButton.setObjectName("addRangeGroupButton")
        self.label_9 = QtWidgets.QLabel(self.tab_3)
        self.label_9.setGeometry(QtCore.QRect(320, 10, 67, 17))
        self.label_9.setObjectName("label_9")
        self.itemsToGroupAttachmentTable = QtWidgets.QTableView(self.tab_3)
        self.itemsToGroupAttachmentTable.setGeometry(QtCore.QRect(10, 30, 311, 391))
        self.itemsToGroupAttachmentTable.setObjectName("itemsToGroupAttachmentTable")
        self.groupVolumeTable = QtWidgets.QTableView(self.tab_3)
        self.groupVolumeTable.setGeometry(QtCore.QRect(330, 30, 311, 391))
        self.groupVolumeTable.setObjectName("groupVolumeTable")
        self.tabs.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.label_4 = QtWidgets.QLabel(self.tab_4)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 231, 17))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.tab_4)
        self.label_5.setGeometry(QtCore.QRect(430, 10, 121, 17))
        self.label_5.setObjectName("label_5")
        self.addEquipmentButton = QtWidgets.QPushButton(self.tab_4)
        self.addEquipmentButton.setGeometry(QtCore.QRect(10, 430, 191, 25))
        self.addEquipmentButton.setObjectName("addEquipmentButton")
        self.equipmentResourceConsumptionTable = QtWidgets.QTableView(self.tab_4)
        self.equipmentResourceConsumptionTable.setGeometry(QtCore.QRect(10, 30, 411, 391))
        self.equipmentResourceConsumptionTable.setObjectName("equipmentResourceConsumptionTable")
        self.equipmentResourcesTable = QtWidgets.QTableView(self.tab_4)
        self.equipmentResourcesTable.setGeometry(QtCore.QRect(430, 30, 211, 391))
        self.equipmentResourcesTable.setObjectName("equipmentResourcesTable")
        self.tabs.addTab(self.tab_4, "")

        self.retranslateUi(Form)
        self.tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Объемное планирование деятельности предприятия"))
        self.makeCalculationButton.setText(_translate("Form", "Рассчитать"))
        self.addItemButton.setText(_translate("Form", "Добавить товар"))
        self.label_12.setText(_translate("Form", "Производимые товары"))
        self.label_13.setText(_translate("Form", "Ограничения выпуска"))
        self.groupBox.setTitle(_translate("Form", "Значимость критериев"))
        self.label_14.setText(_translate("Form", "Max. выпуск"))
        self.label_15.setText(_translate("Form", "Min. себестоимость"))
        self.label_16.setText(_translate("Form", "Max. прибыль"))
        self.loadButton.setText(_translate("Form", "Загрузить"))
        self.saveButton.setText(_translate("Form", "Сохранить"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_6), _translate("Form", "Продукция"))
        self.label_10.setText(_translate("Form", "Оптовые цены"))
        self.label_11.setText(_translate("Form", "Себестоимость"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_5), _translate("Form", "Финансы"))
        self.label.setText(_translate("Form", "Трудозатраты сотрудников"))
        self.label_2.setText(_translate("Form", "Зараб.платы"))
        self.addEmployeeButton.setText(_translate("Form", "Добавить сотрудника"))
        self.label_3.setText(_translate("Form", "Фонд зараб. платы"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab), _translate("Form", "Персонал"))
        self.label_6.setText(_translate("Form", "Расходы сырья"))
        self.addRawMaterialKindButton.setText(_translate("Form", "Добавить вид сырья"))
        self.label_7.setText(_translate("Form", "Ресурсы сырья"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_2), _translate("Form", "Сырье"))
        self.label_8.setText(_translate("Form", "Принадлежность"))
        self.addRangeGroupButton.setText(_translate("Form", "Добавить асс. группу"))
        self.label_9.setText(_translate("Form", "Объемы"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_3), _translate("Form", "Асс.группы"))
        self.label_4.setText(_translate("Form", "Расход ресурсов оборудования"))
        self.label_5.setText(_translate("Form", "Ресурсы"))
        self.addEquipmentButton.setText(_translate("Form", "Добавить оборудование"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_4), _translate("Form", "Оборудование"))

